#include <stdio.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

int main(){
    u_int64_t n = 4000000;
    u_int64_t sum = 0;
    //u_int64_t sum = fibonacci(1, 2, n, 0);

    u_int64_t f_1 = 1;
    u_int64_t f_2 = 2;

    while((f_1 + f_2) <= n){

        u_int64_t cur = (f_1 + f_2);

        if(cur % 2 == 0){
            sum += (f_1 + f_2);
            printf("The sum is: %lld", sum);
        }

        f_1 = f_2;
        f_2 = cur;
    }


    printf("The sum is: %lld", (sum + 2));
    return 0; //Exit success
}
